site_name: Global Data Barometer Handbook
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
  palette:
    primary: cyan
  logo: img/gdb-5.png
plugins:
  - search
  - literate-nav:
      nav_file: menu.md
  - macros:
      include_dir: docs/includes
  - print-site:
        add_cover_page: true
        cover_page_template: "docs/assets/templates/custom_cover_page.tpl"
        #Table of contents
        add_table_of_contents: true
        toc_title: 'Table of Contents'
        toc_depth: 4
        #Content-related
        enumerate_headings: true
        
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - custom.css
